server {
    listen 5174;
    server_name _;

    root /usr/share/nginx/html;

    location /admin/ {
        try_files $uri $uri/ /admin/index.html;
    }

    location /admin {
        return 301 /admin/;
    }
}
